name: Cycled_iOS
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  charts_flutter: ^0.6.0
  intl: any
  animated_theme_switcher: "^1.0.5"
  simple_animations: ^2.2.1
  font_awesome_flutter: ^8.0.1
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  firebase_auth:
  google_sign_in:
  flutter_facebook_login:
  google_maps_flutter: ^0.5.27+3
  geoflutterfire:
  hexcolor: any
  geolocator:

  barcode_scan:
  qr_flutter:
  location:
  cloud_firestore:
  curved_navigation_bar: ^0.3.3
  progress_dialog:
  image_picker:
  firebase_core:
  firebase_storage:
  flutter_markdown: ^0.4.1
  url_launcher:
  percent_indicator: "^2.1.5"
  flutter_svg: ^0.12.1
  pie_chart: ^3.1.1

  share:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/bin.png
    - assets/images/displayPic.png
    - assets/images/rice.png
    - assets/images/factory.png
    - assets/images/plant.png
    - assets/images/waste.png
    - assets/images/carbs.png
    - assets/images/meat.png
    - assets/images/veg.png
    - assets/images/efforts.png
    - assets/images/invitefriend.png
    - assets/images/tokens.png
    - assets/images/arrow.png
    - assets/images/gift.png
    - assets/images/background.png
    - assets/images/Welcome.png
    - assets/images/community.png
    - assets/images/Eat and Shop.png
    - assets/images/third.png
    - assets/images/Legend.png
    - assets/images/secondscreen.png
    - assets/images/pollBG.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.jpg
    - assets/images/3.png
    - assets/images/seedling.jpg
    - assets/images/quiz.jpg
    - assets/images/levels.png
    - assets/images/challenger.png
    - assets/images/poll.jpg
    - assets/images/changer.png
    - assets/images/PolLDetails.png
    - assets/images/instructions.png
    - assets/images/explore.png
    - assets/images/cycler.png
    - assets/images/grass.png
    - assets/images/store.jpg
    - assets/images/profile.png
    - assets/images/community.jpg
    - assets/images/image_01.png
    - assets/images/google.png
    - assets/images/grass.jpg
    - assets/t&c.md
    - assets/privacy_policy.md
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
